CREATE ROLE beautyflow_app
  LOGIN
  PASSWORD 'local-app-password'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOBYPASSRLS;

GRANT CONNECT ON DATABASE beautyflow TO beautyflow_app;
GRANT USAGE ON SCHEMA public TO beautyflow_app;

ALTER DEFAULT PRIVILEGES FOR ROLE beautyflow_admin IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO beautyflow_app;
ALTER DEFAULT PRIVILEGES FOR ROLE beautyflow_admin IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO beautyflow_app;
